[build]
command = "npm install --legacy-peer-deps && react-router build"
publish = "build/client"
NODE_VERSION = "22"

[dev]
command = "react-router dev"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[context.production.environment]
  VITE_PDF_WORKER_SRC = "https://personalwebjacky.netlify.app/pdf.worker.mjs"
